version: "3.9"
services:
  app:
    build: .
    depends_on:
      - "mongo"
    environment:
      MONGOHOST: mongo
    ports:
      - "3000:3000"
    restart: always
  mongo:
    image: mongo:5.0-focal
    restart: always
